config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  resources :homes, only: [:index]
  devise_for :users, controllers: {sessions: 'sessions'}
  resources :users do
    resources :messages, only: [:create]
  end

  get "search/users/:query" => "search#users"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room

  after_create_commit do
    broadcast_append_to self.room, target: "messages", locals:{message: self}
    notify
  end

  def self.last_message(room_name)
    room = Room.find_by(name: room_name)
    if room
      room.messages.order(created_at: :desc).first
    end
  end


  def notify
    sender = User.find(self.sender_id)
    receiver = User.find(self.receiver_id)
    set_current_room_as_seen
    broadcast_update_to "#{self.room.name}_last_msg", target: sender_id, partial: "users/last_message", locals:{user: sender, last_message_date: DateTime.now.strftime("%d %b"), last_message: self.body,  seen_count: unseen_count }
    # update self sidebar
    broadcast_update_to "#{self.room.name}_last_msg", target: receiver_id, partial: "users/last_message", locals:{user: receiver, last_message_date: DateTime.now.strftime("%d %b"), last_message: self.body,  seen_count: 0}
  end

  def unseen_count
    count = self.room.messages.where(receiver_id: self.receiver_id, is_seen: false).count
    return count
  end

  def set_current_room_as_seen
    self.room.messages.where(receiver_id: self.sender_id, is_seen: false).update_all(is_seen: true)
  end

  def self.show_avatar(message)
    current_message = message
    room = Room.find_by(id: message.room_id)
    messages = room.messages.order(:created_at)
    puts "show avatar is called from the view"
    current_message_index = messages.find_index(message)
    prev_message = current_message_index > 0 ? messages[current_message_index - 1] : nil

    return current_message.sender_id == prev_message&.sender_id
  end

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages

  def self.create_private_room(room_name)
    single_room = Room.create(name: room_name)
    single_room
  end

  def self.find_last_message_by_room(room)
    room = Room.find_by(name: room)
    if room
       room.messages.last
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  scope :all_except, ->(user){where.not(id:user)}
  validates :username, presence: true
  has_one_attached :avatar


  after_create_commit {broadcast_append_to "users", target: "users",partial: "users/user", locals: { user: self } }
  after_update_commit do
    broadcast_replace_to  "user_status", partial: "users/status", user: self
    broadcast_replace_to  "sidebar_user_status", target:"#{self.id}_sidebar", partial: "users/sidebar_status", user: self
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  before_action :set_current_user

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])
  end
  def set_current_user
    Current.user = current_user
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_current_user
  # GET /homes or /homes.json
  def index
    @users = User.all_except(current_user)
  end

  private
  def set_current_user
    puts "Setting current user"
    Current.user = current_user
    current_user.update(status: true)
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    if params[:message][:body].empty?
      return
    end
    room = Room.where(name: msg_params[:room_id]).first
    message = Message.new(msg_params)
    message.room = room
    message.save!

  end

  private
  def msg_params
    params.require(:message).permit(:body, :receiver_id, :sender_id, :room_id)
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def users
    query = params[:query]
    users = User.all_except(current_user).where("username LIKE ?", "%#{query}%")
    render json: users
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def destroy
    current_user.update(status: false)
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include RoomsHelper
  before_action :set_user
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_user_id
  def show
    @users = User.all_except(current_user).order(status: :desc)
    @room_name = get_name_by_id(current_user.id, @user.id)
    @room = Room.where(name: @room_name).first || Room.create_private_room(@room_name)
    @first_message_date = @room.messages.order(created_at: :desc).first&.created_at || DateTime.now
    @messages = @room.messages.order(created_at: :asc)
    change_message_status(@messages)
    @message = Message.new
    render 'homes/index'
  end


  private
  def set_user
    @user = User.find(params[:id])
  end

  def invalid_user_id
    redirect_to root_path
  end

  def change_message_status(messages)
    messages.where(receiver_id: current_user.id, is_seen: false).each do |message|
      message.update(is_seen: true)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper

end

app/helpers/messages_helper.rb
module MessagesHelper
  include RoomsHelper

  def find_last_message_and_date(room)
    message = last_message(room)
    if message
      last_message_body = message.body
      last_message_date = message.created_at.strftime("%d %b")
    else
      last_message_body = "No message"
      last_message_date = DateTime.now.strftime("%d %b")
    end
    return last_message_body, last_message_date
  end

  def last_message(room)
    Room.find_last_message_by_room(room)
  end

  def selected_div(user_id, sender_id)
    if user_id == sender_id.to_i
       "bg-background-color border-l-4 border-blue-400"
    else
      "border-b-2"
    end
  end

  def initial_unseen_msg_count(room, user)
    room = Room.find_by(name: room)
    if room
    count = room.messages.where(sender_id: user, is_seen: false).count
      return count
    else
      return 0
    end
  end



end

app/helpers/rooms_helper.rb
module RoomsHelper
  def get_name_by_id(user_1, user_2)
    user = [user_1, user_2].sort
    return "private_#{user[0]}_#{user[1]}"
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_avatar(user_id)
    user = User.find(user_id)
    if user.avatar.attached?
      return url_for(user.avatar)
    else
      return "profile_avatar.jpg"
    end
  end
end

app/views/homes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
 <div class="grid grid-cols-12">
     <div class="col-span-9 rounded bg-white shadow">
       <div class="grid grid-cols-9">
         <div class="h-[90vh] col-span-3 border-r-2   overflow-auto">
           <div class="py-4 px-2 flex justify-between border-b-2">
             <h2 class="">Message</h2>
             <div class="flex">
               <div class="hover:bg-background-color cursor-pointer rounded-lg">
                 <i class="fa-solid fa-circle-plus px-2" style="color: #7c7c7c"></i>
               </div>
               <div class="hover:bg-background-color cursor-pointer rounded-lg">
                  <i class="fa-solid fa-ellipsis-vertical" style="color: #7c7c7c"></i>
               </div>
             </div>
           </div>
           <!--      Search User-->
           <div class="relative" data-controller="search">
             <div class="flex items-center py-2 border-b-2" >
               <i class="fa-solid fa-circle-plus px-2 hover:bg-background-color cursor-pointer rounded-lg" style="color: #7c7c7c"></i>
               <input data-search-target="inputField" data-action="input->search#typed" class="w-full px-4 py-2  rounded-lg focus:outline-none" placeholder="Search user...">
               <i class="fa-solid fa-bars px-2 hover:bg-background-color cursor-pointer rounded-lg" style="color: #7c7c7c"></i>
             </div>
             <div class="absolute w-full bg-white" data-search-target="outputField"></div>
           </div>
           <%= turbo_stream_from "users" %>
           <div id="users" class="">
             <% @users.each do |user| %>
               <%=  render partial: "users/user", locals: {user: user} %>
             <% end %>
           </div>
         </div>
         <div class="h-[90vh] col-span-6 border-2 border-white px-3 rounded-r-lg">
         <% if @user %>
             <div>
           <div class="py-1 flex justify-between items-center">
             <div>
               <div class=" ">
                 <%= @user.username %>
               </div>
<!--               <div class="flex items-center">-->
<!--                 <div class="h-[0.5rem] w-[0.5rem] bg-[#2ac85e] rounded-full"></div>-->
<!--                 <p class="text-sm pl-2 text-gray-700"><%#= @user.status ? "Online" : "Offline" %> </p>-->
<!--               </div>-->
               <%= turbo_stream_from "user_status" %>
               <%= render "users/status", user: @user %>
             </div>
             <i class="fa-solid fa-ellipsis-vertical hover:bg-background-color cursor-pointer rounded-lg" style="color: #7c7c7c"></i>
           </div>
           <div class="pt-2">
             <!--          User + Message div-->
             <div id="scroller_id" class="bg-background-color rounded-t-lg flex flex-col overflow-auto" data-controller="scroll">
               <!--          User details over message section-->
               <div class="flex flex-col items-center pt-2">
                 <div class="h-[6rem] w-[6rem] rounded-full overflow-hidden ">
                   <% if @user.avatar.attached? %>
                     <%= image_tag(@user.avatar, class:"w-full h-full object-cover") %>
                     <% else %>
                   <%= image_tag("profile_avatar.jpg", class:"w-full h-full object-cover") %>
                     <% end %>
                 </div>
                 <div class="font-semibold m-1">
                   <%= @user.username %>
                 </div>
                 <div class="text-gray-700">
                   <%#= @user.email %>
                   Hey there, I'm using Chat
                 </div>
               </div>
<!--               Divider-->
               <div class="relative flex py-2 items-center">
                 <div class="flex-grow border-t border-gray-400"></div>
                 <span class="flex-shrink mx-4 text-gray-400"><%= @first_message_date.strftime('%Y-%m') %></span>
                 <div class="flex-grow border-t border-gray-400"></div>
               </div>
               <!--          Message section-->
               <%= turbo_stream_from @room %>
               <div id="messages" class=" h-[42vh]" >
                 <% @messages.each do |message| %>
                  <%= render partial: "messages/message", locals: {message: message} %>
                 <% end %>
               </div>
             </div>
             <!--          Message form-->
             <div class="w-full">
               <%= render "messages/form" %>
             </div>
           </div>
             </div>
         <% else %>
           <div class="h-[90vh] py-1 flex justify-center items-center">
             <%= render "messages/no_message" %>
           </div>
         <% end %>
       </div>
       </div>
     </div>
<!--   Advertisement section-->
     <div class="col-span-3  mx-4">
       <div class="bg-white  p-4 shadow rounded">
       <span >Advertising</span>
       <div class="py-2">
         <%= image_tag("https://picsum.photos/200") %>
       </div>
       <%= link_to  "Visit website" , root_path, class:"text-blue-700"%>
       </div>
       <div class="flex pt-4">
         <h1 class="text-sm text-gray-700 underline pr-2">Privacy policy</h1>
         <h1 class="text-sm text-gray-700 underline pr-2">Contact us</h1>
         <h1 class="text-sm text-gray-700 underline">Cookies</h1>
       </div>
       <span class="text-sm text-gray-700">Minhaz, 2024</span>
     </div>
 </div>

</div>

app/views/layouts/_nav.html.erb
<nav class="bg-white  flex items-center justify-around py-2">
    <div class="flex flex items-center">
      <%= link_to root_path do %>
      <div class="flex items-center justify-center hover:bg-background-color px-2 py-2 hover:rounded-full">
        <div>
          <i class="fa-solid fa-star-of-life fa-lg" style="color: #696868"></i>
        </div>
      </div>
      <% end %>
      <div class="px-4 mx-2 max-w-48 border-2 rounded-full hover:bg-background-color flex items-center">
        <i class="fa-solid fa-magnifying-glass" style="color: #a1a0a0"></i>
        <input class="w-full px-4 py-1 focus:outline-none" placeholder="Search...">
      </div>
    </div>

    <div class="flex gap-2">

      <%= link_to root_path do %>
        <div class="flex items-center justify-center hover:bg-background-color px-3 py-1 hover:rounded-full">
          <i class="fa-solid fa-house  pr-2" style="color: #696868"></i>
          <h1 class="hidden lg:block  ">Homepage</h1>
        </div>
      <% end %>

      <%= link_to root_path do %>
        <div class="flex items-center justify-center hover:bg-background-color px-3 py-1 hover:rounded-full">
          <i class="fa-solid fa-users  px-2 " style="color: #696868"></i>
          <h1 class="hidden lg:block  ">Connections</h1>
        </div>

      <% end %>


  <%= link_to root_path do %>
    <div class="flex items-center justify-center hover:bg-background-color px-3 py-1 hover:rounded-full">
      <i class="fa-solid fa-message  px-2" style="color: #696868"></i>
      <h1 class="hidden lg:block  ">Messages</h1>
    </div>
  <% end %>

  <%= link_to root_path do %>
    <div class="flex items-center justify-center hover:bg-background-color px-3 py-1 hover:rounded-full">
      <i class="fa-solid fa-bell  px-2" style="color: #696868"></i>
      <h1 class="hidden lg:block pr-2">Notifications</h1>
      <div class="bg-red-500 px-1 h-[1.3rem] w-[1.3rem] text-center rounded-full text-white text-sm">3</div>
    </div>
  <% end %>
      <div class="border-l-2 border-gray-300 my-1">
      </div>
  <%= link_to root_path do %>
    <div class="flex items-center justify-center hover:bg-background-color px-3 py-1 hover:rounded-full">
      <i class="fa-solid fa-screwdriver-wrench  px-2" style="color: #696868"></i>
      <h1 class="hidden lg:block  ">Tools</h1>
    </div>
  <% end %>

  </div>

 <%#= link_to root_path do %>
    <% if current_user  %>
      <div data-controller="toggle" class="relative">
        <button data-action="click->toggle#menu" class=" ">
          <div class="flex items-center hover:bg-background-color px-3 py-1 hover:rounded-full" >
            <div class="px-2">
              <div class="rounded-full h-[2rem] w-[2rem] overflow-hidden ">
                <% if current_user.avatar.attached? %>
                  <%= image_tag(current_user.avatar, class:"w-full h-full object-cover") %>
                <% else %>
                   <%= image_tag("profile_avatar.jpg", class:"w-full h-full object-cover") %>
                  <% end %>
              </div>
            </div>
            <%= current_user.username %>
            <i class="fa-solid fa-caret-down px-2", style="color: #696868"></i>
          </div>
        </button>

        <div data-toggle-target="menu" class="hidden absolute bg-white px-3 lg:px-5 py-2 divide-y-2 border border-gray-300 rounded-lg right-0">
           <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
        </div>
      </div>
    <% else %>
      <div class="flex items-center hover:bg-background-color px-2 py-1 hover:rounded-lg">
        <div class="px-2">
          <div class="rounded-full h-[3rem] w-[3rem] overflow-hidden ">
            <%= image_tag("profile_avatar.jpg") %>
          </div>
        </div>
        <h1 class="font-semibold "> Sign In </h1>
      </div>
    <% end %>
  <%# end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messaging</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="turbo-prefetch" content="false">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style>
      <%= ".msg-#{current_user&.id}-cont" %>{
          display: flex;
          justify-content: flex-end; !important;
      }
      <%= ".msg-#{current_user&.id}-body" %>{
          background-color: rgb(71, 163, 241)
      ; !important;
          color: white;
      }
      <%= ".msg-#{current_user&.id}-avatar" %>{
          display: none;
      }
    </style>
  </head>

  <body class="bg-background-color">
    <%= render "layouts/nav" %>
    <main class="container mx-auto mt-4 px-5 ">
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/_form.erb
<div class="px-2 pb-2 bg-gray-100">
  <%= form_with(model:[@user, @message], url: user_messages_path(@user), data:{controller:"reset-form", action: "turbo:submit-end->reset-form#reset"}) do |f| %>
    <%= f.hidden_field :receiver_id, value: @user.id  %>
    <%= f.hidden_field :sender_id, value: current_user.id %>
    <%= f.hidden_field :room_id, value: get_name_by_id(current_user.id, @user.id) %>
    <div class="flex items-center gap-2 w-full py-2 px-2 bg-white rounded-lg">
      <div class="border-2 border-gray-200 rounded-full py-1">
        <i class="fa-solid fa-circle-plus fa-lg px-2" style="color: #7c7c7c"></i>
      </div>
      <div class="flex flex-grow border-2 px-2 border-gray-200 rounded-full items-center bg-white">
        <%= f.text_field :body, autocomplete: 'off', class:"w-full my-0 border-0  flex-grow focus:ring-0 focus:outline-none"%>
        <i class="fa-regular fa-face-smile fa-lg" style="color: #7c7c7c"></i>
        <%= button_tag type: 'submit', class:"hidden bg-sky-300 px-4 py-2  rounded-r-lg " do %>
          <i class="fa-solid fa-paper-plane"></i>
        <% end %>
      </div>
      <div class="border-2 border-gray-200 rounded-full py-1">
        <i class="fa-solid fa-microphone fa-lg px-2" style="color: #7c7c7c"></i>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/_message.html.erb
<div class="px-1 pb-1 msg-<%= message.sender_id %>-cont flex items-center">
    <div class="h-[1.5rem] w-[1.5rem] rounded-full overflow-hidden msg-<%= message.sender_id %>-avatar">
      <% if !Message.show_avatar(message) %>
       <%= image_tag(user_avatar(message.sender_id), class:"w-full h-full object-cover") %>
        <% else %>
      <div class="w-full h-full object-cover"></div>
      <% end %>
    </div>
    <div class="bg-white text-sm rounded-full px-3 py-2  msg-<%= message.sender_id %>-body max-w-80">
      <h3><%= message.body %></h3>
    </div>
</div>

app/views/messages/_no_message.html.erb
<div class="flex flex-col items-center justify-center">
  <div class="h-2/4 w-2/4">
    <%= image_tag("message.png") %>
  </div>
  <h1 class="text-xl py-2">Message someone and chat right now!</h1>
  <span class="text-xl py-4 bg-[#2563eb] px-4 text-white rounded-full">Get started</span>
</div>

app/views/users/_last_message.html.erb
<%= link_to user, id:"#{user.id}" do %>
<!--  <div id="<%#= user.id %>" >-->
  <%#= seen_count > 0 ? "bg-sky-400": "" %>
      <div class="py-2 px-2 flex items-center hover:bg-background-color <%= seen_count > 0 ? "font-bold": "" %>" >
        <div class="h-[2.5rem] w-[2.5rem] relative">
        <div class="h-[2.5rem] w-[2.5rem] rounded-full overflow-hidden">
          <% if user.avatar.attached? %>
            <%= image_tag(url_for(user.avatar), class:"w-full h-full object-cover") %>
            <div class="h-[0.5rem] w-[0.5rem] <%= user.status ? "bg-[#2ac85e]" : "bg-gray-400"  %>  rounded-full"></div>
          <% else %>
            <%= image_tag("profile_avatar.jpg", class:"w-full h-full object-cover") %>
          <% end %>
        </div>
          <%= turbo_stream_from "sidebar_user_status" %>
          <%= render "users/sidebar_status", user: user %>

      </div>
      <div class="w-full px-2 truncate <%= seen_count > 0 ? "font-bold": "" %>">
        <div class="flex items-center justify-between ">
          <div>
            <%=  user.username %>

            <% if seen_count > 0 %>
              <div class="inline-block bg-green-200 h-[1.2rem] w-[1.2rem] rounded-full text-center">
                <span class="text-xs p-1">
                  <%= seen_count %>
                </span>
              </div>
            <% end %>
          </div>
          <span class="text-sm text-gray-700 "><%= last_message_date %></span>
        </div>
        <div class="truncate">
          <span class="text-sm <%= seen_count > 0 ? "font-bold": "font-light text-gray-600" %>  inline-block "><%= last_message %></span>
        </div>
      </div>
    </div>
<!--  </div>-->
<% end %>



<%#= link_to user do %>
<!--  <div id="<%#= user.id %>" data-controller="user-selection" data-action="click->user-selection#toggleStyle">-->
<!--  <div class="py-2 px-2 flex items-center hover:bg-background-color <%#= user.id == params[:id].to_i  ? "bg-background-color border-l-4 border-blue-500" : "border-b-2" %>">-->
<!--    <div data-user-selection-target="div" class="py-2 px-2 flex items-center hover:bg-background-color ">-->
<!--    <div class="h-[2.5rem] w-[2.5rem] rounded-full overflow-hidden ">-->
      <%# if user.avatar.attached? %>
        <%#= image_tag(url_for(user.avatar), class:"w-full h-full object-cover") %>
      <%# else %>
        <%#= image_tag("profile_avatar.jpg", class:"w-full h-full object-cover") %>
      <%# end %>
<!--    </div>-->
<!--    <div class="w-full px-2 ">-->
<!--      <div class="flex items-center justify-between ">-->
        <%#=  user.username %>
<!--        <span class="text-sm text-gray-700 "><%#= last_message_date %></span>-->
<!--      </div>-->
<!--      <span class="text-sm font-light inline-block truncate"><%#= last_message %></span>-->
<!--    </div>-->
<!--  </div>-->
<!--  </div>-->
<%# end %>

app/views/users/_sidebar_status.html.erb
<%= turbo_frame_tag "sidebar_user_status"%>
<div id="<%=user.id%>_sidebar" class="h-[0.5rem] w-[0.5rem] absolute right-1 bottom-[2px] <%= user.status ? "bg-[#2ac85e]" : "bg-gray-400"  %>  rounded-full"></div>

app/views/users/_status.html.erb
<%= turbo_frame_tag "user_status" %>
<div id="<%= dom_id(user) %>">
  <div class="flex items-center">
    <div class="h-[0.5rem] w-[0.5rem] <%= user.status ? "bg-[#2ac85e]" : "bg-gray-400"  %>  rounded-full"></div>
    <p class="text-sm pl-2 text-gray-700"><%= user.status ? "Online" : "Offline" %> </p>
  </div>
</div>

app/views/users/_user.html.erb
<% room_name =  get_name_by_id(Current.user&.id || 0, user.id)%>
<% last_message_body, last_message_date = find_last_message_and_date(room_name) %>
<%= turbo_stream_from "#{room_name}_last_msg" %>
<div id="<%user.id %>" class=" <%= selected_div(user.id, params[:id]) %>">
  <%= render partial: "users/last_message",
             locals: { user: user,
                       last_message_date: last_message_date,
                       last_message: last_message_body,
                       seen_count: initial_unseen_msg_count(room_name, user.id), } %>
</div>